fix(apiEU): error when get ev_first_departure_time
when `vehicle.ev_first_departure_time` is fetch _get_time_from_string isn't retreivable because of :
```
File "/usr/local/lib/python3.10/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 587, in _update_vehicle_properties
vehicle.ev_first_departure_time = self._get_time_from_string(
File "/usr/local/lib/python3.10/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 276, in _get_time_from_string
value = dt.datetime.strptime(value, "%I%M %p").time()
TypeError: 'NoneType' object is not callable
```